theme: jekyll-theme-minimal
markdown: kramdown
title: "Ruan van Mazijk"
logo: face2.jpg
description: |
  <p>
    A South African ecology and evolutionary biology Masters student at the
    <a href="http://www.biologicalsciences.uct.ac.za/">Dept. of Biological Sciences</a>,
    <a href="http://www.uct.ac.za/">University of Cape Town</a> (UCT).
  </p>
  <p>
    <a href="http://www.uct.ac.za/">
      <img src="https://rvanmazijk.github.io/logos/UCT.png" width="50" height="50" />
    </a>
    <a href="http://www.biologicalsciences.uct.ac.za/">
      <img src="https://rvanmazijk.github.io/logos/BIO.png" width="50" height="50" />
    </a>
    <img src="https://rvanmazijk.github.io/logos/SASSB.png" width="50" height="40" />
  </p>
  <p>
    <a href="https://twitter.com/rvanmazijk">
      <img src="https://rvanmazijk.github.io/logos/Twitter.png" width="16" height="16" /> @rvanmazijk
    </a><br>
    <a href="https://github.com/rvanmazijk">
      <img src="https://rvanmazijk.github.io/logos/GitHub.png" width="16" height="16" /> @rvanmazijk
    </a><br>
    <a href="https://www.researchgate.net/profile/Ruan_Van_Mazijk">
      <img src="logos/ResearchGate-green.jpg" width="16" height="16" /> ResearchGate
    </a>
  </p>
