theme: jekyll-theme-minimal
markdown: kramdown
title: "About the scientist: <br><i>Ruan van Mazijk</i>"
description: |
  <p>
    <img src="face2.jpg"     width="50" height="50" />
    <img src="logos/UCT.png" width="50" height="50" />
    <img src="logos/BIO.png" width="50" height="50" />
  </p>
  <p>
    Hi! I'm Ruan, a South African ecology and evolutionary biology Masters student at the <a href="http://www.biologicalsciences.uct.ac.za/">Dept. of Biological Sciences</a>, <a href="http://www.uct.ac.za/">University of Cape Town</a> (UCT).
  </p>
  <a
    class="twitter-timeline"
    data-width="300"
    data-height="500"
    href="https://twitter.com/rvanmazijk?ref_src=twsrc%5Etfw"
  >
    Tweets by rvanmazijk
  </a>
  <script
    async
    src="https://platform.twitter.com/widgets.js"
    charset="utf-8"
  ></script>
