theme: jekyll-theme-minimal
markdown: kramdown
title: "Ruan van Mazijk"
logo: face2.jpg
description: |
  <p>
    A South African ecology and evolutionary biology Masters student at the
    <a href="http://www.biologicalsciences.uct.ac.za/">Dept. of Biological Sciences</a>,
    <a href="http://www.uct.ac.za/">University of Cape Town</a> (UCT).
  </p>
  <p>
    <a href="http://www.uct.ac.za/">
      <img 
        src="https://github.com/rvanmazijk/rvanmazijk.github.io/raw/master/logos/UCT.png"
        width="75" height="75"
      />
    </a>
    <a href="http://www.biologicalsciences.uct.ac.za/">
      <img
        src="https://github.com/rvanmazijk/rvanmazijk.github.io/raw/master/logos/BIO.png"
        width="75" height="75"
      />
    </a>
  </p>
